// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt1zok8LbwZnS_mODG_gJwOK90JYLIePI',
    appId: '1:358326743764:web:48f39b336bbccc74d10141',
    messagingSenderId: '358326743764',
    projectId: 'kel8-semaikan',
    authDomain: 'kel8-semaikan.firebaseapp.com',
    storageBucket: 'kel8-semaikan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIailyHxWl292MF1xTGPNJTSA25-gdSY4',
    appId: '1:358326743764:android:c733348445c144cdd10141',
    messagingSenderId: '358326743764',
    projectId: 'kel8-semaikan',
    storageBucket: 'kel8-semaikan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9kUFGB6Bo8XcLiCvMH1UkdGnB6GMnlyw',
    appId: '1:358326743764:ios:1330888a37fc993bd10141',
    messagingSenderId: '358326743764',
    projectId: 'kel8-semaikan',
    storageBucket: 'kel8-semaikan.firebasestorage.app',
    iosBundleId: 'com.example.semaikan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9kUFGB6Bo8XcLiCvMH1UkdGnB6GMnlyw',
    appId: '1:358326743764:ios:1330888a37fc993bd10141',
    messagingSenderId: '358326743764',
    projectId: 'kel8-semaikan',
    storageBucket: 'kel8-semaikan.firebasestorage.app',
    iosBundleId: 'com.example.semaikan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt1zok8LbwZnS_mODG_gJwOK90JYLIePI',
    appId: '1:358326743764:web:c30eb98f71c43ce2d10141',
    messagingSenderId: '358326743764',
    projectId: 'kel8-semaikan',
    authDomain: 'kel8-semaikan.firebaseapp.com',
    storageBucket: 'kel8-semaikan.firebasestorage.app',
  );
}
