// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52Xt04-kjnqc9TbnkQAC3lQ_9QUqAlUI',
    appId: '1:848737160015:web:be22a96036473c38eed33a',
    messagingSenderId: '848737160015',
    projectId: 'semaikan-5fa4e',
    authDomain: 'semaikan-5fa4e.firebaseapp.com',
    storageBucket: 'semaikan-5fa4e.firebasestorage.app',
    measurementId: 'G-DYT96109Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFTDQ8hcZ-tYrPG-l40QKK90EohtuZgZ4',
    appId: '1:848737160015:android:e59ab8ce6413f466eed33a',
    messagingSenderId: '848737160015',
    projectId: 'semaikan-5fa4e',
    storageBucket: 'semaikan-5fa4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdApAT1Wc3akSejT7yMhqBUdYnvY9N-Jk',
    appId: '1:848737160015:ios:8e06d74da3eeb138eed33a',
    messagingSenderId: '848737160015',
    projectId: 'semaikan-5fa4e',
    storageBucket: 'semaikan-5fa4e.firebasestorage.app',
    iosBundleId: 'com.example.semaikan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdApAT1Wc3akSejT7yMhqBUdYnvY9N-Jk',
    appId: '1:848737160015:ios:8e06d74da3eeb138eed33a',
    messagingSenderId: '848737160015',
    projectId: 'semaikan-5fa4e',
    storageBucket: 'semaikan-5fa4e.firebasestorage.app',
    iosBundleId: 'com.example.semaikan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB52Xt04-kjnqc9TbnkQAC3lQ_9QUqAlUI',
    appId: '1:848737160015:web:3d732eec85aa5266eed33a',
    messagingSenderId: '848737160015',
    projectId: 'semaikan-5fa4e',
    authDomain: 'semaikan-5fa4e.firebaseapp.com',
    storageBucket: 'semaikan-5fa4e.firebasestorage.app',
    measurementId: 'G-J0V9EQYNQP',
  );
}
